spring:
  profiles: dev1
server:
  port: 8080
  
spring:
  profiles: dev2
server:
  port: 9999
  
productService:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8080, localhost:9999
    ServerListRefreshInterval: 15000
